### ISSUE TITLE
Experiment Cluster Preview

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#1]
When inspecting / modifying an experiment or when benchmarking add the possibility to preview the detected duplicates of a dataset as clusters.

**Comment by phpfs** [comment]
How far has this been processed in the backend so far?

**Comment by phpfs** [comment]
True positives are displayed as clusters by default. For false positives & false negatives, the view does not make much sense. We will therefore close this issue until further notice :)

(Please use a new issue if more attention is needed!)
