### ISSUE TITLE
npm run start-api does fail after access

### ISSUE THREAD

**Issue by gremmlinMTW** [HPI-Information-Systems/snowman#102]
**Describe the bug**
when building from source and trying to start the backend via "npm run start-api", after accessing with the browser the following error pops up:
info: Using storage directory /var/lib/jenkins/workspace/snowman/wrapper/storage
info: Preparing database...
error: Object.values(...).filter(...).map(...).flat is not a function {"name":"TypeError","stack":"TypeError: Object.values(...).filter(...).map(...).flat is not a function\n    at TableCreator.foreignKeyConstraints (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/table/creator.js:118:14)\n    at TableCreator.constraints (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/table/creator.js:100:47)\n    at TableCreator.createTableQuery (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/table/creator.js:80:148)\n    at TableCreator.createTable (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/table/creator.js:43:47)\n    at Table.create (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/table/table.js:71:68)\n    at TableInstaller.installTables (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/setup/install.js:59:42)\n    at Object.installTables (/var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/setup/install.js:45:81)\n    at /var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/setup/setup.js:78:35\n    at sqliteTransaction (/var/lib/jenkins/workspace/snowman/wrapper/node_modules/better-sqlite3/lib/transaction.js:58:24)\n    at /var/lib/jenkins/workspace/snowman/wrapper/dist/api/database/setup/setup.js:80:23"}
Finished: SUCCESS

 

**To Reproduce**
run via jenkins on ubuntu 20.04
git clone...
npm install
cd ./app 
npm install
cd ../wrapper 
npm install
npm run start-api

**Expected behavior**
a UI to show up

**Additional context**

**Comment by martingraf4** [comment]
Which version of NodeJS have you used? the `Array.flat` method is implemented [from `11.0.*` onwards](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility).

We recommend using NodeJS version `14.x` or later as we do not test earlier versions.
