### ISSUE TITLE
Support F*-metric

### ISSUE THREAD

**Issue by Lasklu** [HPI-Information-Systems/snowman#142]
As we know some researches argue that using the f-measure[ is not recommended](https://spiral.imperial.ac.uk/bitstream/10044/1/46235/2/stco-d-16-00349-final.pdf) to evaluate the performance of a classification run. 
Instead, they propose the usage of [F*](https://link.springer.com/article/10.1007/s10994-021-05964-1).
We should support this in our benchmark as a metric.

**Comment by phpfs** [comment]
This is already included in v2.0.0 :)
