### ISSUE TITLE
Bugfix: Experiments with same name

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#144]
When selecting two experiments with the same name, the following error is thrown: 
![image](https://user-images.githubusercontent.com/49309285/113591125-ce165280-9633-11eb-90af-85c213fe5d46.png)

To reproduce:
![image](https://user-images.githubusercontent.com/49309285/113591151-d7072400-9633-11eb-845b-f5b660d0bd91.png)

The experiment id should be used as key instead.

**Comment by phpfs** [comment]
Resolved now - we didn't use a proper key for the option reminders ;)
