### ISSUE TITLE
Bugfix N-ary Metrics Page: Multiple metrics with same value

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#145]
Opening the n-ary metrics page with two metrics being the same causes the following key error:

![image](https://user-images.githubusercontent.com/49309285/113591579-5ac11080-9634-11eb-96e5-867eee468c54.png)

To reproduce:
![image](https://user-images.githubusercontent.com/49309285/113591592-614f8800-9634-11eb-966f-6f614df95086.png)

A combination of experiment id and metric identifier/name should be used instead.

**Comment by phpfs** [comment]
I'll take care of this :)
