### ISSUE TITLE
UI should differentiate between experiments used as gold standard

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#15]
For binary comparison, one of the two supplied experiments is regarded as a gold standard. We should make it clear in the UI which one the user wants to use as gold standard.

**Comment by florian-papsdorf** [comment]
The branch feature/vivid-benchmark-configurator allows only one gold standard and differs between chosen experiment and chosen gold standard by drag n drop the related elements in the related area.
