### ISSUE TITLE
Include cypress as an optional dependency

### ISSUE THREAD

**Issue by phpfs** [HPI-Information-Systems/snowman#161]
The cypress e2e testing framework needs several minutes to install and should therefore only be used in case integrations test are run. Therefore, I'd suggest to make it an optional dependency.

**Comment by martingraf4** [comment]
We can leave out a few installs in the workflows in general.

- lint
  - `npm i` in app
  - `npm i` in wrapper
- build
  - `npm i` in ./

**Comment by phpfs** [comment]
@martingraf4 Did you test this? :) For me, the build dependencies seem to be required since some types were moved to the root directory.

**Comment by martingraf4** [comment]
No I did not test that
