### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by haolonghu** [HPI-Information-Systems/snowman#172]
**Describe the bug**
I used the acmsigmod 2021 and loaded "output.csv" of "X2.csv",then it crashed
**To Reproduce**
Just select and submit

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: [Windows ]
- Version [10]

**Additional context**

**Comment by martingraf4** [comment]
Did you make sure that your file has the correct format (separator: `,`, quote: `"`, escape: `"`) and to select `sigmod2021` as file format when uploading the experiment?

If that does not help: Could you share your `output.csv` file and the log file at `%appdata%\snowman-wrapper\combined.log`? I will then try to reproduce your error.

**Comment by haolonghu** [comment]
Thanks
I have solved this,it is because of some error datas.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin ***@***.***&gt;; 
发送时间: 2021年4月27日(星期二) 晚上10:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HPI-Information-Systems/snowman] Crash (#172)





 
Did you make sure that your file has the correct format (separator: ,, quote: ", escape: ") and to select sigmod2021 as file format when uploading the experiment?
 
If that does not help: Could you share your output.csv file and the log file at %appdata%\snowman-wrapper\combined.log? I will then try to reproduce your error.
