### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#20]
We should add the following types of tests

- API tests (e.g. check correctness of routes)
- e2e / integration tests (e.g. via Cypress)
- performance tests (check that magellan dataset can be uploaded in less than _x_ min)

Additionally the test coverage of our unit tests should be improved by testing edge cases like 

1. upload dataset (no file)
2. upload experiment
3. upload dataset file with too few records and see if error is thrown

**Comment by florian-papsdorf** [comment]
In frontend, at least testing validation logic or selection array logic could be useful. Until now, I don't see such an advantage if we test reducers-

**Comment by phpfs** [comment]
#94 added integration test with cypress. More tests are needed in frontend.
