### ISSUE TITLE
snowman” cannot be opened because the developer cannot be verified. - Mac

### ISSUE THREAD

**Issue by harsh-var** [HPI-Information-Systems/snowman#227]
**Unable to launch Snowman on Mac **

Downloaded the latest dmg available - snowman-3.2.3-mac. Launched dmg and moved snow man to application folder. Navigated to the Application folder, right clicked on the snowman launch icon and clicked open. 

**To Reproduce**
1. Go to '.application folder.'
2. Control + Click on '.snowman launch icon..'
3. Click on to '.Open.'

“snowman” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
Safari downloaded this file today at 12:49 PM from objects.githubusercontent.com.

**Expected behavior**
I want to launch Snowman and try it out on this machine.

**Screenshots**
<img width="266" alt="image" src="https://user-images.githubusercontent.com/82447657/169476769-2da5c2d1-e027-407c-8b79-9f3461ca0dc8.png">

**Desktop (please complete the following information):**
- OS: [e.g. Windosws]
- Version [e.g. 10]
- Squeak version [e.g. 5.3]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/82447657/169476200-6b3e99d5-07a6-4b6b-b87a-2ab4ff391cc8.png">

**Additional context**

**Comment by phpfs** [comment]
Hi @harsh-var,

thank you very much for bringing this up!
Snowman is indeed at this time not signed as this would require an Apple Developer account. But - this does not mean that you can't try it out. Simply follow these steps:
1. Attempt to open snowman.app (either from within the .dmg or after copying it to your local Applications folder)
2. On the warning message about missing signature, click "Cancel".
3. Open System Preferences and had to the Security Page and select the "General" tab.
4. It should show that it blocked snowman.app from running - now click on "Open anyways".
5. (You do not need to do this every time you open snowman, but rather only for the first time - or after downloading a new version!)

In case your first want to take a look at would you've been downloading, feel free to take a look at the [Github Actions `Release` workflow](https://github.com/HPI-Information-Systems/snowman/actions/workflows/release.yml). On this page, you can directly download the build results and investigate the code commit that it was based upon. For the highest degree of certainty, you can also quite easily build Snowman on your local compute.

Have fun and let us know your feedback :)

Best, phpfs
