### ISSUE TITLE
Include markdown file on how to add an experiment format

### ISSUE THREAD

**Issue by phpfs** [HPI-Information-Systems/snowman#35]
Adding new experiments is pretty easy. Therefore, it makes sense to include a special contribution guide just for this use case.

Should we put this in our docs or a README into the experiment formats folder?

**Comment by martingraf4** [comment]
I would create a "contributing" section in the docs and link it in the main README (it probably makes sense to have that in one central location, right?).

**Comment by phpfs** [comment]
This is added now
