### ISSUE TITLE
Clarify what tupleCount contains

### ISSUE THREAD

**Issue by phpfs** [HPI-Information-Systems/snowman#84]
We need to clarify wether the tupleCount endpoint returns numbers with or without blank rows included. Either way, we'd have a bug in our application. (only on develop)

**Comment by phpfs** [comment]
@martingraf4 can you help with this? :)

**Comment by martingraf4** [comment]
Has been changed to `numberRows` and `numberPairs`. Does this solve the issue?

**Comment by martingraf4** [comment]
I have implemented the correct usage in  #79
